export interface Food {
  id: string
  name: string
  category: string
  servingSize: string
  servingUnit: string
  calories: number
  protein: number // grams
  carbs: number // grams
  fats: number // grams
  fiber: number // grams
}

export const foodDatabase: Food[] = [
  // PROTEINS
  {
    id: 'chicken_breast',
    name: 'Chicken Breast (cooked)',
    category: 'Protein',
    servingSize: '100',
    servingUnit: 'g',
    calories: 165,
    protein: 31,
    carbs: 0,
    fats: 3.6,
    fiber: 0,
  },
  {
    id: 'salmon',
    name: 'Salmon (cooked)',
    category: 'Protein',
    servingSize: '100',
    servingUnit: 'g',
    calories: 206,
    protein: 22,
    carbs: 0,
    fats: 13,
    fiber: 0,
  },
  {
    id: 'ground_beef',
    name: 'Ground Beef (90% lean)',
    category: 'Protein',
    servingSize: '100',
    servingUnit: 'g',
    calories: 180,
    protein: 24,
    carbs: 0,
    fats: 9,
    fiber: 0,
  },
  {
    id: 'eggs',
    name: 'Eggs (large)',
    category: 'Protein',
    servingSize: '1',
    servingUnit: 'egg',
    calories: 78,
    protein: 6,
    carbs: 0.6,
    fats: 5.3,
    fiber: 0,
  },
  {
    id: 'greek_yogurt',
    name: 'Greek Yogurt (plain)',
    category: 'Protein',
    servingSize: '100',
    servingUnit: 'g',
    calories: 59,
    protein: 10,
    carbs: 3.3,
    fats: 0.4,
    fiber: 0,
  },
  {
    id: 'cottage_cheese',
    name: 'Cottage Cheese',
    category: 'Protein',
    servingSize: '100',
    servingUnit: 'g',
    calories: 98,
    protein: 11,
    carbs: 3.9,
    fats: 5,
    fiber: 0,
  },
  {
    id: 'tuna',
    name: 'Tuna (canned in water)',
    category: 'Protein',
    servingSize: '100',
    servingUnit: 'g',
    calories: 96,
    protein: 22,
    carbs: 0,
    fats: 0.8,
    fiber: 0,
  },
  {
    id: 'whey_protein',
    name: 'Whey Protein Powder',
    category: 'Protein',
    servingSize: '30',
    servingUnit: 'g',
    calories: 120,
    protein: 25,
    carbs: 2,
    fats: 1,
    fiber: 0,
  },

  // CARBS
  {
    id: 'white_rice',
    name: 'White Rice (cooked)',
    category: 'Carbs',
    servingSize: '100',
    servingUnit: 'g',
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fats: 0.3,
    fiber: 0.4,
  },
  {
    id: 'brown_rice',
    name: 'Brown Rice (cooked)',
    category: 'Carbs',
    servingSize: '100',
    servingUnit: 'g',
    calories: 111,
    protein: 2.6,
    carbs: 23,
    fats: 0.9,
    fiber: 1.8,
  },
  {
    id: 'oats',
    name: 'Oats (dry)',
    category: 'Carbs',
    servingSize: '40',
    servingUnit: 'g',
    calories: 150,
    protein: 5,
    carbs: 27,
    fats: 3,
    fiber: 4,
  },
  {
    id: 'sweet_potato',
    name: 'Sweet Potato (cooked)',
    category: 'Carbs',
    servingSize: '100',
    servingUnit: 'g',
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fats: 0.1,
    fiber: 3,
  },
  {
    id: 'banana',
    name: 'Banana',
    category: 'Carbs',
    servingSize: '1',
    servingUnit: 'medium',
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fats: 0.3,
    fiber: 3.1,
  },
  {
    id: 'white_bread',
    name: 'White Bread',
    category: 'Carbs',
    servingSize: '1',
    servingUnit: 'slice',
    calories: 79,
    protein: 2.7,
    carbs: 14,
    fats: 1,
    fiber: 0.7,
  },
  {
    id: 'whole_wheat_bread',
    name: 'Whole Wheat Bread',
    category: 'Carbs',
    servingSize: '1',
    servingUnit: 'slice',
    calories: 80,
    protein: 4,
    carbs: 14,
    fats: 1,
    fiber: 2.4,
  },
  {
    id: 'pasta',
    name: 'Pasta (cooked)',
    category: 'Carbs',
    servingSize: '100',
    servingUnit: 'g',
    calories: 131,
    protein: 5,
    carbs: 25,
    fats: 1.1,
    fiber: 1.8,
  },

  // FATS
  {
    id: 'olive_oil',
    name: 'Olive Oil',
    category: 'Fats',
    servingSize: '1',
    servingUnit: 'tbsp',
    calories: 119,
    protein: 0,
    carbs: 0,
    fats: 13.5,
    fiber: 0,
  },
  {
    id: 'almonds',
    name: 'Almonds',
    category: 'Fats',
    servingSize: '28',
    servingUnit: 'g',
    calories: 164,
    protein: 6,
    carbs: 6,
    fats: 14,
    fiber: 3.5,
  },
  {
    id: 'peanut_butter',
    name: 'Peanut Butter',
    category: 'Fats',
    servingSize: '2',
    servingUnit: 'tbsp',
    calories: 188,
    protein: 8,
    carbs: 7,
    fats: 16,
    fiber: 2,
  },
  {
    id: 'avocado',
    name: 'Avocado',
    category: 'Fats',
    servingSize: '100',
    servingUnit: 'g',
    calories: 160,
    protein: 2,
    carbs: 9,
    fats: 15,
    fiber: 7,
  },
  {
    id: 'coconut_oil',
    name: 'Coconut Oil',
    category: 'Fats',
    servingSize: '1',
    servingUnit: 'tbsp',
    calories: 117,
    protein: 0,
    carbs: 0,
    fats: 13.5,
    fiber: 0,
  },
  {
    id: 'walnuts',
    name: 'Walnuts',
    category: 'Fats',
    servingSize: '28',
    servingUnit: 'g',
    calories: 185,
    protein: 4.3,
    carbs: 3.9,
    fats: 18.5,
    fiber: 1.9,
  },

  // VEGETABLES
  {
    id: 'broccoli',
    name: 'Broccoli (cooked)',
    category: 'Vegetables',
    servingSize: '100',
    servingUnit: 'g',
    calories: 34,
    protein: 2.8,
    carbs: 7,
    fats: 0.4,
    fiber: 2.4,
  },
  {
    id: 'spinach',
    name: 'Spinach (cooked)',
    category: 'Vegetables',
    servingSize: '100',
    servingUnit: 'g',
    calories: 23,
    protein: 2.7,
    carbs: 3.6,
    fats: 0.4,
    fiber: 2.2,
  },
  {
    id: 'carrot',
    name: 'Carrot (cooked)',
    category: 'Vegetables',
    servingSize: '100',
    servingUnit: 'g',
    calories: 35,
    protein: 0.7,
    carbs: 8,
    fats: 0.2,
    fiber: 2.3,
  },
  {
    id: 'bell_pepper',
    name: 'Bell Pepper',
    category: 'Vegetables',
    servingSize: '100',
    servingUnit: 'g',
    calories: 31,
    protein: 1,
    carbs: 6,
    fats: 0.3,
    fiber: 2,
  },

  // FRUITS
  {
    id: 'apple',
    name: 'Apple',
    category: 'Fruits',
    servingSize: '1',
    servingUnit: 'medium',
    calories: 95,
    protein: 0.5,
    carbs: 25,
    fats: 0.3,
    fiber: 4.4,
  },
  {
    id: 'orange',
    name: 'Orange',
    category: 'Fruits',
    servingSize: '1',
    servingUnit: 'medium',
    calories: 62,
    protein: 1.2,
    carbs: 15,
    fats: 0.3,
    fiber: 3.1,
  },
  {
    id: 'blueberries',
    name: 'Blueberries',
    category: 'Fruits',
    servingSize: '100',
    servingUnit: 'g',
    calories: 57,
    protein: 0.7,
    carbs: 14,
    fats: 0.3,
    fiber: 2.4,
  },
]

// Search foods by name
export const searchFoods = (query: string): Food[] => {
  const lowerQuery = query.toLowerCase()
  return foodDatabase.filter((food) => food.name.toLowerCase().includes(lowerQuery))
}

// Get foods by category
export const getFoodsByCategory = (category: string): Food[] => {
  return foodDatabase.filter((food) => food.category === category)
}

// Get all categories
export const getAllCategories = (): string[] => {
  const categories = new Set(foodDatabase.map((food) => food.category))
  return Array.from(categories)
}

// Calculate nutrition for multiple servings
export const calculateNutrition = (food: Food, servings: number) => {
  return {
    calories: Math.round(food.calories * servings),
    protein: Math.round(food.protein * servings * 10) / 10,
    carbs: Math.round(food.carbs * servings * 10) / 10,
    fats: Math.round(food.fats * servings * 10) / 10,
    fiber: Math.round(food.fiber * servings * 10) / 10,
  }
}

